### ISSUE TITLE
time slider looks different in main view and loading dialog

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/agave#101]
## Use Case

no reason why time slider shouldn't have consistent look.

## Solution

Time Series Interactive Element: Make identical on loading dialog and Main Screen

**Comment by ShrimpCryptid** [comment]
I think this actually doesn't need a fix anymore! The reason why the time slider looks different at initialization is because it doesn't have a range set yet. It looks consistent with the loading dialogue once a timescale dataset is loaded.

The pull request here (https://github.com/allen-cell-animated/agave/pull/126) hides the time window until a timescale dataset is loaded, at which point the time slider will be correctly initialized. The only problem I can see is if the user decides to manually open the time slider window (View>Time).

![image](https://github.com/allen-cell-animated/agave/assets/30200665/4c82e9f3-8f9d-4e19-a8cd-f4ac9dc830dd)
^ *is hidden by default before loading*
![image](https://github.com/allen-cell-animated/agave/assets/30200665/85d6becc-7d7d-4be0-83e7-edd491e77ac0)
^ *consistent once dataset is loaded*

I could add in dummy range values if we want it to look consistent even if it's not visible by default.

**Comment by toloudis** [comment]
Sounds reasonable to me.  Thanks for looking at this. 
@TravisKroeker should take a peek too.  
Incidentally, @ShrimpCryptid do you have the ability to test agave on macOS also?

**Comment by ShrimpCryptid** [comment]
Travis and I had a conversation last week and he noted that this behavior is fine, so I'm closing this issue ticket!
